services:
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: homework_assignment
    ports:
      - "3306:3306"
    volumes:
      - ./init_db.sql:/docker-entrypoint-init_db.d/init_db.sql
